services:
  csapiexample:
    container_name: csapiexample
    image: csapiexample
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5000:5000
    networks:
      - host-net
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: "Server=db;Database=Example;User Id=sa;Password=Your_password123;"
      
  db:
    container_name: db
    build:
      context: ./Db
      dockerfile: ./Dockerfile
    networks:
      - host-net
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -Q "SELECT 1" || exit 1
      retries: 10
    restart: always
  
networks:
  host-net: