services:
  csapiexample:
    container_name: csapiexample
    image: csapiexample
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - ./dev.env
      
  db:
    container_name: db
    build:
      context: ./Db
      dockerfile: ./Dockerfile
    ports:
      - 1433:1433
    env_file:
      - ./dev.env