apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      labels:
        app: api-pod
    spec:
      containers:
      - name: api-container
        image: csapiexample:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: ASPNETCORE_URLS
            value : http://+:5000
          - name: ASPNETCORE_ENVIRONMENT
            value : Development
          - name: CONNECTION_STRING
            value : Server=db-service.default.svc.cluster.local;Database=Example;User Id=sa;Password=Your_password123;
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
          initialDelaySeconds: 90
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-pod
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer

