apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-pod
  template:
    metadata:
      labels:
        app: db-pod
    spec:
      containers:
      - name: db-container
        image: cs-api-example_db:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "2.5Gi"
            cpu: "250m"
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: Your_password123
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: data
          mountPath: /var/opt/mssql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  loadBalancerIP: 10.0.0.240
  selector:
    app: db-pod
  ports:
  - port: 1433
    targetPort: 1433
  type: LoadBalancer


