apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      app: db-pod
  template:
    metadata:
      labels:
        app: db-pod
    spec:
      containers:
      - name: db-container
        image: db:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "2.5Gi"
            cpu: "250m"
        env:
          - name: SA_PASSWORD
            value: "Your_password123"
          - name: ACCEPT_EULA
            value: "Y"
        ports:
        - containerPort: 1433

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: LoadBalancer
  selector:
    app: db-pod
  ports:
  - port: 1433
    targetPort: 1433

